module.exports.names = [
    "Wanderer's Nest Hostel",
    "Backpacker’s Haven",
    "Explorer's Retreat",
    "Adventure Lodge",
    "Cityscape Hostel",
    "Urban Nomad Hostel",
    "Serenity Stay",
    "Cozy Corner Hostel",
    "Roaming Roots Hostel",
    "Chill & Chat Hostel",
    "The Travellers' Inn",
    "Dreamers' Den Hostel",
    "Voyagers' Villa",
    "Nomad Nook Hostel",
    "Pathfinders' Hostel",
    "Horizon Hostel",
    "The Rustic Retreat",
    "Global Gather Hostel",
    "Epic Journey Hostel",
    "Hiker's Haven Hostel",
    "Wanderlust Way",
    "Sunny Side Hostel",
    "Maple Leaf Hostel",
    "Ocean Breeze Hostel",
    "Starlight Stay Hostel",
    "The Backpacker’s Hub",
    "The Local Experience Hostel",
    "Crossroads Hostel",
    "Sunset Haven Hostel",
    "Pioneer Hostel"
]

module.exports.description = [
    "Welcome to Wanderer's Nest Hostel, your cozy sanctuary in the heart of the city. Perfectly situated close to major attractions and vibrant neighborhoods, our hostel provides a warm and welcoming environment for travelers from around the world. Enjoy comfortable dorms and private rooms, all equipped with modern amenities. Relax in our inviting common areas, share stories with fellow wanderers, and start your day with a complimentary breakfast. Whether you're here for a quick stopover or an extended stay, Wanderer's Nest is your home away from home.",
    "Discover the ultimate retreat for adventurers at Backpacker's Haven. Located in a lively area, our hostel offers a vibrant atmosphere, perfect for socializing and meeting new friends. We provide clean and comfortable dormitories as well as private rooms, all designed with the budget traveler in mind. Enjoy our communal kitchen, cozy lounge, and nightly events that bring guests together. With friendly staff and a wealth of local knowledge, Backpacker's Haven ensures you have an unforgettable stay.",
    "Embark on your next adventure at Explorer's Retreat, where comfort meets convenience. Situated near key attractions and transport links, our hostel offers spacious dorms and private rooms, all designed to provide a restful escape after a day of exploration. Our knowledgeable staff are on hand to offer travel tips and recommendations, ensuring you make the most of your visit. Enjoy free Wi-Fi, complimentary breakfast, and a range of activities that connect you with other explorers.",
    "For thrill-seekers and outdoor enthusiasts, Adventure Lodge is the ideal base. Located close to some of the best adventure spots, our hostel offers easy access to hiking, biking, and outdoor activities. Choose from a variety of accommodation options, including dorms and private rooms, all featuring comfortable beds and modern facilities. Join our adventure tours, socialize in our communal spaces, and unwind with a drink at our on-site bar. At Adventure Lodge, every day is an adventure.",
    "Experience the city in style at Cityscape Hostel. Our modern, chic hostel offers panoramic views and contemporary amenities, providing a luxurious stay at an affordable price. Located in the heart of the city, you'll be just steps away from top attractions, dining, and entertainment. Enjoy our stylish dorms and private rooms, relax in our sleek lounge, and take advantage of our fully equipped kitchen. Cityscape Hostel is your perfect urban getaway.",
    "Stay at Urban Nomad Hostel, where style meets convenience. Our hostel offers a unique blend of modern design and a friendly atmosphere, making it a top choice for urban explorers. Located in a trendy neighborhood, you'll have easy access to the city's best spots. Relax in our spacious dorms and private rooms, enjoy high-speed Wi-Fi, and connect with fellow travelers in our vibrant communal areas. Urban Nomad Hostel is your ideal home base for exploring the city.",
    "Find your peaceful retreat at Serenity Stay. Tucked away in a quiet corner of the city, our hostel offers a tranquil escape with comfortable accommodations and serene surroundings. Choose from cozy dorms or private rooms, each designed to provide a restful experience. Enjoy our beautiful garden, unwind in the lounge, and start your day with a complimentary breakfast. Serenity Stay is the perfect place to relax and recharge.",
    "Welcome to Cozy Corner Hostel, where warmth and hospitality meet. Our charming hostel provides a comfortable and homely atmosphere, with well-kept dorms and private rooms. Located in a friendly neighborhood, you'll feel right at home from the moment you arrive. Take advantage of our communal kitchen, lounge by the fireplace, and join our social events. Cozy Corner Hostel is your perfect home away from home.",
    "Embrace the spirit of travel at Roaming Roots Hostel. Our hostel celebrates the global community of travelers, offering a warm and inviting space for all. Enjoy our comfortable dorms and private rooms, each thoughtfully designed with a touch of home. Meet fellow travelers in our communal areas, participate in cultural events, and take advantage of our local travel tips. Roaming Roots Hostel is where your journey begins.",
    "Chill & Chat Hostel is the ultimate social hub for travelers. Our hostel offers a relaxed and friendly environment, perfect for meeting new people and sharing experiences. Choose from comfortable dorms or private rooms, and enjoy our spacious lounge, communal kitchen, and regular social events. Located close to major attractions and nightlife, Chill & Chat Hostel ensures you have a fun and memorable stay.",
    "A classic hostel experience with all the essentials for budget travelers.",
    "A creative haven for dreamers and artists, featuring unique decor and inspiring spaces.",
    "Luxurious yet affordable, Voyagers' Villa offers upscale amenities in a hostel setting.",
    "An intimate, welcoming hostel that feels like a second home.",
    "Ideal for adventurers, offering maps, guides, and a communal spirit.",
    "Enjoy stunning views and modern facilities at Horizon Hostel.",
    "A charming, rustic hostel with wooden interiors and a cozy fireplace.",
    "A melting pot of cultures, Global Gather offers diverse activities and international cuisine.",
    "Perfect for epic adventures, this hostel provides adventure planning services and gear rental.",
    "Ideal for hikers, offering trail maps, gear storage, and a hearty breakfast.",
    "For those with a case of wanderlust, this hostel provides travel inspiration and resources.",
    "Bright and cheerful, Sunny Side Hostel offers sunny rooms and a vibrant garden.",
    "A cozy, Canadian-themed hostel with friendly service and warm decor.",
    "Enjoy the sea breeze at this beachside hostel, offering water sports and coastal views.",
    "A magical stay under the stars, with rooftop stargazing and comfortable rooms.",
    "The ultimate hub for backpackers, offering everything from tours to social events.",
    "Immerse yourself in local culture with authentic experiences and homely accommodations.",
    "A vibrant, bustling hostel located at the crossroads of major travel routes.",
    "Experience breathtaking sunsets and a relaxed atmosphere at Sunset Haven.",
    "For the modern pioneer, offering innovative amenities and a spirit of discovery."
];


